# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.1.0/NCSSK.srcs/sources_1/ip/c_addsub_1/c_addsub_1.xci
# IP: The module: 'c_addsub_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.1.0/NCSSK.srcs/sources_1/ip/c_addsub_1/c_addsub_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.1.0/NCSSK.srcs/sources_1/ip/c_addsub_1/c_addsub_1.xci
# IP: The module: 'c_addsub_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.1.0/NCSSK.srcs/sources_1/ip/c_addsub_1/c_addsub_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
