# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2/pynq-z2_v1.0.xdc

# IP: ip/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet
