# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2/pynq-z2_v1.0.xdc

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# Block Designs: bd/mod_cpu_ps/mod_cpu_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps || ORIG_REF_NAME==mod_cpu_ps} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_processing_system7_0_0/mod_cpu_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_processing_system7_0_0 || ORIG_REF_NAME==mod_cpu_ps_processing_system7_0_0} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_axi_gpio_0_0/mod_cpu_ps_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_axi_gpio_0_0 || ORIG_REF_NAME==mod_cpu_ps_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_axi_gpio_0_1/mod_cpu_ps_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_axi_gpio_0_1 || ORIG_REF_NAME==mod_cpu_ps_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_axi_gpio_0_2/mod_cpu_ps_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_axi_gpio_0_2 || ORIG_REF_NAME==mod_cpu_ps_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_axi_gpio_0_3/mod_cpu_ps_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_axi_gpio_0_3 || ORIG_REF_NAME==mod_cpu_ps_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_axi_gpio_0_4/mod_cpu_ps_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_axi_gpio_0_4 || ORIG_REF_NAME==mod_cpu_ps_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_ps7_0_axi_periph_0/mod_cpu_ps_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_ps7_0_axi_periph_0 || ORIG_REF_NAME==mod_cpu_ps_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_rst_ps7_0_50M_0/mod_cpu_ps_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_rst_ps7_0_50M_0 || ORIG_REF_NAME==mod_cpu_ps_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_xbar_0/mod_cpu_ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_xbar_0 || ORIG_REF_NAME==mod_cpu_ps_xbar_0} -quiet] -quiet

# IP: bd/mod_cpu_ps/ip/mod_cpu_ps_auto_pc_0/mod_cpu_ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mod_cpu_ps_auto_pc_0 || ORIG_REF_NAME==mod_cpu_ps_auto_pc_0} -quiet] -quiet

# XDC: bd/mod_cpu_ps/mod_cpu_ps_ooc.xdc
