######################################################################
#
# File name : tb_NCSSK_wave.do
# Created on: Sat Nov 14 00:20:49 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
