# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Users/benji/OneDrive/FPGA_Project/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/ip/c_sub_0/c_sub_0.xci
# IP: The module: 'c_sub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/benji/OneDrive/FPGA_Project/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/ip/c_sub_0/c_sub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_sub_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Users/benji/OneDrive/FPGA_Project/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/ip/c_sub_0/c_sub_0.xci
# IP: The module: 'c_sub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/benji/OneDrive/FPGA_Project/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/ip/c_sub_0/c_sub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_sub_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
