# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.2.1/NCSSK.srcs/sources_1/bd/mod_cpu_ps/ip/mod_cpu_ps_processing_system7_0_0/mod_cpu_ps_processing_system7_0_0.xci
# IP: The module: 'mod_cpu_ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.2.1/NCSSK.srcs/sources_1/bd/mod_cpu_ps/ip/mod_cpu_ps_processing_system7_0_0/mod_cpu_ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mod_cpu_ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.2.1/NCSSK.srcs/sources_1/bd/mod_cpu_ps/ip/mod_cpu_ps_processing_system7_0_0/mod_cpu_ps_processing_system7_0_0.xci
# IP: The module: 'mod_cpu_ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/benji/OneDrive/FPGA_Project/NCSSK_copy_v1.2.1/NCSSK.srcs/sources_1/bd/mod_cpu_ps/ip/mod_cpu_ps_processing_system7_0_0/mod_cpu_ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mod_cpu_ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
