# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivadoPrj/2018.2/NCSSK/NCSSK.srcs/sources_1/ip/cordic_2/cordic_2.xci
# IP: The module: 'cordic_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivadoPrj/2018.2/NCSSK/NCSSK.srcs/sources_1/ip/cordic_2/cordic_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/vivadoPrj/2018.2/NCSSK/NCSSK.srcs/sources_1/ip/cordic_2/cordic_2.xci
# IP: The module: 'cordic_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivadoPrj/2018.2/NCSSK/NCSSK.srcs/sources_1/ip/cordic_2/cordic_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
