######################################################################
#
# File name : tb_NCSSK_wave.do
# Created on: Tue Dec 01 20:23:09 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
