######################################################################
#
# File name : tb_NCSSK_compile.do
# Created on: Sun Nov 08 05:44:55 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2019.2\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0" \
"../../../../NCSSK.srcs/sources_1/ip/cordic_1/cordic_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/cordic_2/cordic_2_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/c_sub_1/c_sub_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/mult_gen_1/mult_gen_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/mult_gen_0/mult_gen_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/c_sub_0/c_sub_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/cordic_0/cordic_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/xfft_0/xfft_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/new/NCSSK_top.v" \
"../../../../NCSSK.srcs/sources_1/new/fft_signal.v" \
"../../../../NCSSK.srcs/sources_1/new/get_phase.v" \
"../../../../NCSSK.srcs/sources_1/new/get_phase_difference.v" \
"../../../../NCSSK.srcs/sources_1/new/get_pitch_angle.v" \
"../../../../NCSSK.srcs/sources_1/new/phase_diff_times_kesai.v" \
"../../../../NCSSK.srcs/sources_1/new/rom_read_signal.v" \
"../../../../NCSSK.srcs/sim_1/new/tb_NCSSK.v" \


# compile glbl module
D:\\modeltech64_2019.2\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

