######################################################################
#
# File name : tb_NCSSK_simulate.do
# Created on: Sat Nov 14 15:10:14 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L dist_mem_gen_v8_0_12 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_NCSSK xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_NCSSK_wave.do}

view wave
view structure
view signals

do {tb_NCSSK.udo}

run 1000ns
