######################################################################
#
# File name : tb_NCSSK_simulate.do
# Created on: Fri Nov 13 02:32:56 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L dist_mem_gen_v8_0_12 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_NCSSK xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_NCSSK_wave.do}

view wave
view structure
view signals

do {tb_NCSSK.udo}

run 1000ns
