######################################################################
#
# File name : tb_NCSSK_wave.do
# Created on: Sat Nov 07 20:45:35 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
