######################################################################
#
# File name : tb_NCSSK_compile.do
# Created on: Fri Dec 04 00:52:56 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xilinx_vip
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xil_defaultlib
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xpm
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/dist_mem_gen_v8_0_12

D:\\modeltech64_2019.2\\win64\\vmap xilinx_vip modelsim_lib/msim/xilinx_vip
D:\\modeltech64_2019.2\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
D:\\modeltech64_2019.2\\win64\\vmap xpm modelsim_lib/msim/xpm
D:\\modeltech64_2019.2\\win64\\vmap dist_mem_gen_v8_0_12 modelsim_lib/msim/dist_mem_gen_v8_0_12

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work xilinx_vip  "+incdir+D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/ec67/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/5bb9/hdl/verilog" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/70fd/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0" "+incdir+D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

D:\\modeltech64_2019.2\\win64\\vcom -64 -93 -work xpm  \
"D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/ec67/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/5bb9/hdl/verilog" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/70fd/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0" "+incdir+D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../NCSSK.srcs/sources_1/ip/c_addsub_1/c_addsub_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/cordic_1/cordic_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/cordic_2/cordic_2_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/c_sub_1/c_sub_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/mult_gen_1/mult_gen_1_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/mult_gen_0/mult_gen_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/div_gen_0/div_gen_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/ip/c_addsub_0/c_addsub_0_sim_netlist.v" \

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work dist_mem_gen_v8_0_12  "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/ec67/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/5bb9/hdl/verilog" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/70fd/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0" "+incdir+D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../NCSSK.ip_user_files/ipstatic/simulation/dist_mem_gen_v8_0.v" \

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/ec67/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/5bb9/hdl/verilog" "+incdir+../../../../NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/70fd/hdl" "+incdir+../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0" "+incdir+D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../NCSSK.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../../NCSSK.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v" \
"../../../../NCSSK.srcs/sources_1/new/NCSSK_top.v" \
"../../../../NCSSK.srcs/sources_1/new/get_angle.v" \
"../../../../NCSSK.srcs/sources_1/new/get_zero_diff.v" \
"../../../../NCSSK.srcs/sources_1/new/phase_diff_times_kesai.v" \
"../../../../NCSSK.srcs/sources_1/new/rom_read_signal.v" \
"../../../../NCSSK.srcs/sources_1/new/zero_point_find.v" \
"../../../../NCSSK.srcs/sim_1/new/tb_NCSSK.v" \

# compile glbl module
D:\\modeltech64_2019.2\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

