# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include e:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/ec67/hdl {
      E:/2018.2/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/2018.2/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      E:/2018.2/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include e:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/bd/mod_cpu_ps/ipshared/ec67/hdl {
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_processing_system7_0_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_axi_gpio_0_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_axi_gpio_0_1_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_axi_gpio_0_2_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_axi_gpio_0_3_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_axi_gpio_0_4_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_rst_ps7_0_50M_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_xbar_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mod_cpu_ps_auto_pc_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/dist_mem_gen_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mult_gen_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/c_sub_1_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/cordic_1_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/cordic_2_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/mult_gen_1_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/clk_wiz_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/c_addsub_1_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/c_addsub_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/div_gen_0_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/realtime/c_addsub_2_stub.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/bd/mod_cpu_ps/synth/mod_cpu_ps.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/new/NCSSK_top.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/new/get_angle.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/new/phase_diff_cal.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/new/phase_diff_times_kesai.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/new/rom_read_signal.v
      E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/NCSSK.srcs/sources_1/bd/mod_cpu_ps/hdl/mod_cpu_ps_wrapper.v
    }
      rt::read_vhdl -lib xpm E:/2018.2/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mod_cpu_ps_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "E:/vivadoPrj/GIt/Git/NCSSK/prj_Vivado_18_2/NCSSK/.Xil/Vivado-252-LAPTOP-EE4FFACC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
